=== StormNs/XMLProject/web/schema/movies.xsd
<?xml version="1.0"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">
    <xs:element name="movies" type="movieList"/>
    <xs:complexType name="movieList">
        <xs:sequence>
            <xs:element name="movie" type="movieType" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="movieType">
        <xs:sequence>
            <xs:element name="name" type="xs:string" minOccurs="1" />
            <xs:element name="alternateName" type="xs:string" minOccurs="0" />
            <xs:element name="description" type="xs:string" minOccurs="0"  />
            <xs:element name="country" type="xs:string" minOccurs="0" />
            <xs:element name="runtime" type="xs:string" minOccurs="0" />
            <xs:element name="language" type="xs:string" minOccurs="0" />
            <xs:element name="releaseDate" type="xs:string" minOccurs="0" />
            <xs:element name="rating" type="xs:decimal" minOccurs="0" />
            <xs:element name="imageCover" type="xs:string"  minOccurs="0"/>
            <xs:element name="director" type="xs:string"  minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== StormNs/XMLProject/web/schema/newXMLDocument.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->


<movies xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xmlns='http://www.netbean.movie'
    xsi:schemaLocation='http://www.netbean.movie movies.xsd'>
    <movie>
        <name>Baby Driver</name>
        <description>After being coerced into working for a crime boss, a young getaway driver finds himself taking part in a heist doomed to fail.</description>
        <country>UK USA</country>
        <runtime>1h 52min</runtime>
        <language>English</language>
        <releaseDate>30 June 2017 (Vietnam)</releaseDate>
        <rating>8.4</rating>
        <imageCover>https://images-na.ssl-images-amazon.com/images/M/MV5BMjM3MjQ1MzkxNl5BMl5BanBnXkFtZTgwODk1ODgyMjI@._V1_UX182_CR0,0,182,268_AL_.jpg</imageCover>
        <director>Edgar Wright</director>
    </movie>
</movies>
